# Generated by Django 5.1.6 on 2025-03-04 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartorder',
            name='payment_status',
            field=models.CharField(choices=[('Paid', 'Paid'), ('Processing', 'Processing'), ('COD Pending', 'COD Pending'), ('Failed', 'Failed')], default='Processing', max_length=100),
        ),
    ]
