# Generated by Django 5.1.6 on 2025-03-03 19:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userauths', '0003_user_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='full_name',
        ),
    ]
